# Generated by Django 4.0.1 on 2022-02-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productshop', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_bag', to='productshop.product', verbose_name='Product in Bag')),
            ],
            options={
                'verbose_name': 'Product in Bag',
                'verbose_name_plural': 'Products in Bag',
                'db_table': 'product_in_bag',
            },
        ),
    ]
